import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <div class="navbar bg-green-500">
            <div class="navbar-start">
              <h1 class="btn btn-ghost text-xl">Blog</h1>
            </div>
            <div class="navbar-center lg:flex">
              <ul className="flex gap-3">
                <li>
                  <Link href="/"> Home</Link>
                </li>
                <li>
                  <Link href="/profile"> Profile</Link>
                </li>
              </ul>
            </div>
            <div class="navbar-end">
              <a class="btn">Login</a>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
